import { createAsyncThunk, createSlice, PayloadAction } from '@reduxjs/toolkit';
import { RootState, AppThunk } from '../store';
import bookAPI from 'apis/bookApi';
import { BookType, ReviewType } from './type';

export interface BookState {
  books: BookType[];
  bookReviews: ReviewType[];
  status: 'idle' | 'loading' | 'failed';
}

const initialState: BookState = {
  books: [],
  bookReviews: [],
  status: 'idle',
};

export const getBooksAsync = createAsyncThunk('books/fetchBooks', async () => {
  const response = await bookAPI.getListBestSellerBooks();
  return response.books;
});
export const getReviewsAsync = createAsyncThunk(
  'books/fetchBookReviews',
  async (title: string | null) => {
    const response = await bookAPI.getReviewsByTitle(title);
    return response;
  },
);

export const booksSlice = createSlice({
  name: 'books',
  initialState,
  reducers: {},
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(getBooksAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getBooksAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.books = action.payload;
      })
      .addCase(getBooksAsync.rejected, (state) => {
        state.status = 'failed';
      })
      .addCase(getReviewsAsync.pending, (state) => {
        state.status = 'loading';
      })
      .addCase(getReviewsAsync.fulfilled, (state, action) => {
        state.status = 'idle';
        state.bookReviews = action.payload;
      });
  },
});

export default booksSlice.reducer;
const { actions, reducer } = booksSlice;
export { actions as BookActions, reducer as BooksReducer };
